export const CAR_BRANDS: { brand: string; models: string[] }[] = [
  { brand: "Audi", models: ["A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8"] },
  { brand: "BMW", models: ["Serija 1", "Serija 3", "Serija 5", "Serija 7", "X1", "X3", "X5", "X6", "X7"] },
  { brand: "Citroën", models: ["C1", "C3", "C4", "C5", "Berlingo", "Jumpy"] },
  { brand: "Dacia", models: ["Sandero", "Duster", "Logan", "Lodgy", "Jogger"] },
  { brand: "Fiat", models: ["500", "Panda", "Punto", "Tipo", "Doblo", "Bravo"] },
  { brand: "Ford", models: ["Fiesta", "Focus", "Mondeo", "Kuga", "S-Max", "Puma", "Transit"] },
  { brand: "Honda", models: ["Civic", "Accord", "CR-V", "HR-V", "Jazz"] },
  { brand: "Hyundai", models: ["i10", "i20", "i30", "Tucson", "Santa Fe", "Kona"] },
  { brand: "Kia", models: ["Picanto", "Rio", "Ceed", "Sportage", "Sorento", "Stonic"] },
  { brand: "Mazda", models: ["2", "3", "6", "CX-3", "CX-5", "CX-30"] },
  { brand: "Mercedes-Benz", models: ["A-klasa", "B-klasa", "C-klasa", "E-klasa", "S-klasa", "GLA", "GLC", "GLE"] },
  { brand: "Nissan", models: ["Micra", "Juke", "Qashqai", "X-Trail", "Navara"] },
  { brand: "Opel", models: ["Corsa", "Astra", "Insignia", "Mokka", "Grandland", "Zafira"] },
  { brand: "Peugeot", models: ["208", "308", "508", "2008", "3008", "5008", "Partner"] },
  { brand: "Renault", models: ["Clio", "Megane", "Captur", "Kadjar", "Scenic", "Talisman"] },
  { brand: "Škoda", models: ["Fabia", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq"] },
  { brand: "Seat", models: ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco"] },
  { brand: "Suzuki", models: ["Swift", "Vitara", "SX4", "Jimny", "Baleno"] },
  { brand: "Toyota", models: ["Yaris", "Corolla", "Camry", "RAV4", "C-HR", "Hilux", "Land Cruiser"] },
  { brand: "Volkswagen", models: ["Polo", "Golf", "Passat", "Tiguan", "Touareg", "T-Roc", "Arteon", "Caddy"] },
  { brand: "Volvo", models: ["S60", "S90", "V40", "V60", "XC40", "XC60", "XC90"] },
  { brand: "Ostalo", models: ["Ostalo"] },
];
